name: QuickExplore
version: "0.4.1"
api-version: "1.15"
main: dev.ad585.spigot.quickexplore.QuickExplore
author: ad585
description: Allows players to teleport to random far away locations to explore
commands:
    quickexplore:
        aliases: ["qe", "explore", "startquest"]
        description: Teleports you far away (for a price) in hopes that you find riches
        permission: quickexplore.use
    qequit:
        aliases: ["qquit"]
        description: "Returns player from quest (if exploring) and refunds them if refund time has not expired"
        permission: quickexplore.quit
    qelist:
        aliases: ["qlist"]
        description: "Send player a list of all available quests"
        permission: quickexplore.list
    qetime:
        aliases: ["qtime"]
        description: "Tells player the time remaining to complete their quest (if exploring)"
        permission: quickexplore.time
permissions:
    quickexplore.*:
        description: "Give access for all commands"
        children:
            quickexplore.quit: true
            quickexplore.list: true
            quickexplore.time: true
    quickexplore.use:
        description: "Allows player to explore"
        default: true
    quickexplore.quit:
        description: "Allows player to quit a current quest"
        default: true
    quickexplore.list:
        description: "Allows player to view all possible quests"
        default: true
    quickexplore.time:
        description: "Allows player to know remaining time"
        default: true
